---
- name: Installing OCP Standalone Registry in a Single Node
  hosts: registry
  tasks:
    - name: Preparing OCP node for OCR
      include_role:
        name: ocp_configure_node
      vars:
        node_type: registry

    - name: Cloning OpenShift-Ansible playbooks to the localhost
      command: git clone https://github.com/openshift/openshift-ansible ./openshift-ansible/{{ openshift_ansible_version }}
      delegate_to: localhost

    - name: Checking out branch {{ openshift_ansible_version }}
      command: git checkout {{ openshift_ansible_version }}
      args:
        chdir: openshift-ansible/{{ openshift_ansible_version }}
      delegate_to: localhost

    - include: htpasswd_tasks.yml
      when: id_provider == 'htpasswd'

    - name: Installing OCR
      import_playbook: openshift-ansible/{{ openshift_ansible_version }}/playbooks/byo/config.yml
...